# Generated by Django 5.0.1 on 2024-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tradingsymbol', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.CharField(blank=True, max_length=255, null=True)),
                ('strike', models.FloatField(default=0.0)),
                ('tick_size', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_size', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('name_alice', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_token_alice', models.CharField(blank=True, max_length=255, null=True)),
                ('segment_alice', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_symbol_alice', models.CharField(blank=True, max_length=255, null=True)),
                ('name_angel', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_token_angel', models.CharField(blank=True, max_length=255, null=True)),
                ('segment_angel', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_symbol_angel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
